### ISSUE TITLE
matchingRegionsSelector results in an array?

### ISSUE THREAD

**Issue by cveld** [wbuchwalter/tsRedux#3]
I am trying to get your example running. I get the an exception due to the following connection:

``` javascript
$ngRedux.connect(matchingRegionsSelector, this.onMatchingRegionsChanged.bind(this));
```

The exception is as follows:

```
Error: Invariant Violation: `mapStateToScope` must return an object. Instead received .
    at Object.invariant [as default] (browser.js:42)
    at getStateSlice (connector.js:76)
    at Object.connect (connector.js:42)
    at new RegionListerController (regionLister.ts:26)
    at Object.invoke (angular.js:4478)
    at ident.$get.extend.instance (angular.js:9136)
    at nodeLinkFn (angular.js:8248)
    at compositeLinkFn (angular.js:7680)
    at compositeLinkFn (angular.js:7684)
    at publicLinkFn (angular.js:7555)
```

The invariant-checker checks against a regular object, but the variable contains the value [], and therefore throws.

By the way, I had to polish the package.json towards some more recent versions:

``` javascript
"dependencies": {
    "angular": "^1.4.3",
    "awesome-typescript-loader": "^0.7.1",
    "jquery": "^2.1.4",
    "json-loader": "^0.5.2",
    "lodash": "^3.10.0",
    "ng-redux": "^3.0.2",
    "redux": "^3.0.0",
    "reflect-metadata": "^0.1.0",
    "reselect": "^2.0.0",
    "typescript": "^1.6.0",
    "webpack": "^1.10.2"
  },
  "devDependencies": {
    "html-loader": "^0.3.0",
    "html-webpack-plugin": "^1.6.0",
    "simple-typescript-loader": "^1.0.1"
  }
```

And had to change the following lines due to what could be an api change?
In the files permissionActionCreators.ts and regionActionCreators.ts:

``` javascript
return redux.bindActionCreators(actionCreator, $ngRedux.getStore().dispatch);
```

changed to:

``` javascript
return redux.bindActionCreators(actionCreator, $ngRedux.dispatch);
```

**Comment by wbuchwalter** [comment]
Hey Carl!
Yea tsRedux was done with the ngRedux < 1.0.0 and not maintained since then. Considering ngRedux API changed a lot since then it's maybe not the best example ;)

For your particular error, `matchingRegionsSelector` returns an array, but `connect` needs an object (see the full doc [here](https://github.com/wbuchwalter/ng-redux#createstorewithreducer-middlewares-storeenhancers) ), so instead you need to do something like:

``` JS
$ngRedux.connect(
  state => ({ regions: matchingRegionsSelector }), 
  this.onMatchingRegionsChanged.bind(this)
);
```

This is because `connect` will then merge this object with your controller (or whatever the `this` arg you pass is), and you can't merge an array with an object.

**Comment by cveld** [comment]
I really like to dig a bit more into this Redux world and get my head around it :)
Maybe your example was not the best starting point, but still I want to persist in order to play with all the patterns you have applied.

Could it be that in the current example the `mapDispatchToProps` functions should be rewritten?
E.g. 

``` javascript
      $ngRedux.connect(
          state =>
            state.regionsVisualProperties.map,
          regionUIMap =>
            this.regionUIMap = regionUIMap
      );
```

It does not make sense to me to assign a function-expression (`regionUIMap`) to a viewmodel property (`this.regionUIMap`)? Or is this some `$ngRedux` magic below the covers?

Anyways, currently I see that `onMatchingRegionsChanged` is called with a function expression, and `_.forEach` is trying to iterate through a function expression. Does not sound right to me. Somehow I need to get the data behind the function expression, or? 

Bottomline, it currently rains exceptions like the following:

```
TypeError: Cannot read property 'isExpanded' of undefined
    at RegionListerController.regionActions.isExpanded (http://localhost:8080/bundle.js:729:42)
```

Etc.

`isExpanded` is defined as follows:

``` javascript
this.isExpanded = function (id) {
            return _this.regionUIMap[id].isExpanded;
        };
```

When Angular calls `isExpanded` the `id` property has the value of `undefined`. The view is defined as follows:

``` html
<div  ng-repeat='regionId in vm.visibleRegionIds'  ...
```

`onMatchingRegionsChanged` being responsible for populating `vm.visibleRegionIds`, it looks like  it is emitting an array of `[undefined]` due to a wrong iteration through a function expression. I think it should emit an empty array `[]`?

The definition of `onMatchingRegionsChanged`:

``` javascript
  onMatchingRegionsChanged(matchingRegionIds: string[]) {
    //we don't want to just show the matching regions, we want to show their full hierarchy
    this.visibleRegionIds.length = 0;
    _.forEach(matchingRegionIds, id =>
        this.addHierarchy(id, this.visibleRegionIds
        ))
  }
```

**Comment by wbuchwalter** [comment]
Take a look at the [documentation](https://github.com/wbuchwalter/ng-redux#connectmapstatetotarget-mapdispatchtotargettarget), the correct syntax for the arguments of `connect` is explained in details.
The correct syntax for the RegionListerController would be something along those lines (I didn't tried it):

``` JS
 class RegionListerController {

 constructor($ngRedux, private regionActions: IRegionActionCreator) {
    $ngRedux.connect(state => ({
      regionMap: state.regions.regionMap,
      regionUiMap: state.regionsVisualProperties.map,
      matchingRegionIds: matchingRegionsSelector(state)
    }))(this.onSelectedStateChanged);
  }

  onSelectedStateChanged(selectedState) {
    this.regionMap = selectedState.regionMap
    this.regionUIMap = selectedState.regionUIMap
    //we don't want to just show the matching regions, we want to show their full hierarchy
    this.visibleRegionIds.length = 0;
    _.forEach(selectedState.matchingRegionIds, id => this.addHierarchy(id, this.visibleRegionIds))
  }
  //Rest of the code
 }
```

**Comment by cveld** [comment]
Great! Your suggestion works! Albeit you made one slight typo, regionUiMap -> regionUIMap. I'll forgive :) I just submitted a pull request. What do you think? And by the way, if your original TypeScript example is outdated, do you have another one you would to share with me?

**Comment by wbuchwalter** [comment]
Thx for the pull request, that's nice!
I don't have another TypeScript example with angular 1, but you could take a look at some ES6 examples [here](https://github.com/wbuchwalter/ng-redux/tree/master/examples) and [here](https://github.com/neilff/redux-examples), it will be pretty much the same thing.
